# config/settings.yml
defaults: &defaults
  domain: 'localhost:3000'


######################################################################################
development:
  <<: *defaults


######################################################################################
test:
  <<: *defaults


######################################################################################
production:
  <<: *defaults

